Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.10"
  
  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 6000
    v.cpus = 4
  end

  #SSH forwarded port
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true

  config.vm.provision :shell, inline: "sudo apt update"
  config.vm.provision :shell, inline: "sudo apt install vim htop git -y"
end
