Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.10"
  #config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 6000
    v.cpus = 4
  end

  #SSH forwarded port
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true

  config.vm.provision :shell, inline: "sudo apt update"
  config.vm.provision :shell, inline: "sudo apt install ansible git -y"
  config.vm.provision :shell, inline: "rm -fr /vagrant/provision-linux"
  config.vm.provision :shell, inline: "git clone https://github.com/jrmanes/provision-linux.git /vagrant/provision-linux"


  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose  = "vvv"
    ansible.install  = true
     ansible.limit = 'all,localhost'
    ansible.extra_vars = {
      username: "vagrant",
      hosts: "localhost"
    }
    ansible.playbook = "/vagrant/provision-linux/main.yml"
  end

end
